service: team2-device-calibrations

provider:
  name: aws
  runtime: python3.9
  role: arn:aws:iam::697978558555:role/Device-Calibration-Data-Process-Role
  stage: dev
  region: us-west-2

functions:
  process:
    handler: src/handler.lambda_handler

custom:
  apiGatewayUri: "arn:aws:apigateway:${self:provider.region}:lambda:path/2015-03-31/functions/${self:service}-${self:provider.stage}-process/invocations"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: Team2TestDeviceCalibrationGithubAction

    ApiGatewayResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: devicecalibration

    ApiGatewayMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        ResourceId:
          Ref: ApiGatewayResource
        HttpMethod: POST
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: ${self:custom.apiGatewayUri}

    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi

    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        DeploymentId:
          Ref: ApiGatewayDeployment
        StageName: ${self:provider.stage}