service: device-calibrations
provider:
  name: aws
  runtime: python3.9
  role: arn:aws:iam::697978558555:role/Device-Calibration-Data-Process-Role
  stage: dev
  region: us-west-2
# Check
functions:
  process:
    handler: src/handler.lambda_handler