service: device-calibrations

provider:
  name: aws
  runtime: python3.9
  role: arn:aws:iam::697978558555:role/Device-Calibration-Data-Process-Role
  stage: dev
  region: us-west-2
# Check
functions:
  process:
    handler: src/handler.lambda_handler

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: Team2TestDeviceCalibrationGithubAction

    DeviceCalibrationResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        PathPart: devicecalibration

    DeviceCalibrationMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        HttpMethod: POST
        ResourceId:
          Ref: DeviceCalibrationResource
        RestApiId:
          Ref: ApiGatewayRestApi
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri:
            Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAtt process.Arn}/invocations"

    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi

    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        DeploymentId:
          Ref: ApiGatewayDeployment
        StageName: ${self:provider.stage}